---
title: "p8105_hw6_yz4437.Rmd"
author: "Yuchen Zhang"
date: "2022-12-01"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

set.seed(1)
```

##Problem 2


```{r}
homicide_data = read_csv("data/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city, state, sep = ", "),
    resolved = as.numeric(disposition == "Closed by arrest")
         ) %>% 
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO","Tulsa, AL"))) %>%
  filter(victim_race %in% c("White", "Black"), victim_age != "Unknown") %>% 
  mutate(
    victim_age = as.numeric(victim_age),
    victim_race = fct_relevel(victim_race, "White")
    )
```

```{r}
Baltimore_logistic = 
  homicide_data %>%
  filter(city == "Baltimore") %>% 
  select(city_state, resolved, victim_age, victim_race, victim_sex) %>%
  glm(resolved ~ victim_age + victim_race + victim_sex, data = ., family = binomial()) 

#save as an R object
save(Baltimore_logistic, file = "results/Baltimore_logistic.RData")

Baltimore_logistic
```



```{r}
Baltimore_logistic %>% 
  broom::tidy()%>% 
  mutate(lower_conf = confint(Baltimore_logistic)[,1],
         upper_conf = confint(Baltimore_logistic)[,2]) %>% 
  filter(term =='victim_sexMale') %>% 
  select(estimate, lower_conf, upper_conf) %>% 
  mutate(estimate = exp(estimate),
         lower_conf = exp(lower_conf),
         upper_conf = exp(upper_conf))
```

Now run glm for each of the cities:

```{r}
cities_df = 
  homicide_data %>% 
  select(city_state, victim_race:victim_sex, resolved) %>% 
  nest(sample = victim_race:resolved) %>% 
  mutate(
    models = map(sample, ~glm(resolved ~ victim_age+victim_race+victim_sex, family= binomial(link = "logit"), data=.x)),
    results = map(models, broom::tidy),
    conf_int = map(models, ~confint(.x,"victim_sexMale"))
  ) %>% 
  select(city_state,results,conf_int) %>% 
  unnest(results) %>% 
  unnest_wider(conf_int) %>% 
  filter(term == 'victim_sexMale') %>% 
  select(city_state,estimate,`2.5 %`,`97.5 %`) %>% 
  #convert to odds scale
  mutate(
    OR=exp(estimate),
    `2.5 %` =exp(`2.5 %`),
    `97.5 %` = exp(`97.5 %`)
    ) %>% 
    select(OR,`2.5 %`,`97.5 %`)

cities_df 
```

```{r}
cities_df %>% 
ggplot(aes(x=fct_reorder(city_state, estimate), y=estimate))+
  geom_point()+
  geom_errorbar(aes(ymin=`2.5 %`, ymax=`97.5 %`))+
  labs(title = "Number of unsolved homocide among cities", )+xlab("City")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

##Problem 3


